version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672" # AMQP port
            - "15672:15672" # Management UI port
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        restart: unless-stopped

    redis:
        image: redis:6-alpine
        ports:
            - "6379:6379"
        restart: unless-stopped

    fastapi-app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - /app/__pycache__
        environment:
            - PYTHONPATH=/app
            - PYTHONUNBUFFERED=1
            - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672//
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        restart: unless-stopped
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
        depends_on:
            - rabbitmq
            - redis

    celery-worker:
        build: .
        volumes:
            - .:/app
            - /app/__pycache__
        environment:
            - PYTHONPATH=/app
            - PYTHONUNBUFFERED=1
            - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672//
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        restart: unless-stopped
        command: celery -A services.queue_service worker --loglevel=info
        depends_on:
            - rabbitmq
            - redis

volumes:
    rabbitmq_data:
